name: PR check

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        # Using --no-optional to reduce vulnerabilities
        run: npm ci --no-optional

      - name: Build packages (Compile contracts, generate contract types and compile typescript)
        run: npm run build

      - name: Build type checking
        if: success()
        run: npx tsc --project tsconfig.type-checking.json

      - name: Run test
        run: npm test
      
      - name: Run contract upgrade test
        run: npm run test:truffle
