name: Publish packages

on:
  push:
    branches:
      - 'DOI-768-*'

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  publish-packages:
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build packages (Generate contract types and compile typescript)
        run: npm run build

      - name: Run test
        run: npm test

      - name: Set npm credentials
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> $HOME/.npmrc

      - name: Publish packages
        run: npm semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
